apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  duration: "20s"
  selector:
    labelSelectors:
      "app": "nginx"
  scheduler:
    cron: "@every 1m"
